### ISSUE TITLE
Idea: should we add '(..)' to the PickFirstLetters strategy ?

### ISSUE THREAD

**Issue by ClotildeToullec** [reda-idtaleb/label_contractor#5]
It would show that the basename was shortened.

For example:
'myVeryLongFileName.txt'
 would become
'myVeryLo(..).txt'

Maybe it adds too much characters ? To be discussed...

**Comment by reda-idtaleb** [comment]
i think too, the user will immediately notice that the reduction is applied.

**Comment by reda-idtaleb** [comment]
we added just '..'
fix #5
